default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["SQL_USERNAME"] || 'postgres' %>
  password: <%= ENV["SQL_PASSWORD"] || 'postgres' %>
  host: <%= ENV["SQL_HOST"] || 'localhost' %>

development:
  <<: *default
  database: reservation_development

test:
  <<: *default
  database: reservation_test

production:
  <<: *default
  database: reservation_production
